name: Pulse
version: '${version}'
main: dev.aledlb.pulse.Pulse
api-version: '1.21'
folia-supported: true
load: STARTUP
authors: [ aledlb ]
description: Advanced server core plugin with modular architecture
website: https://github.com/aledlb8/pulse
softdepend: [ PlaceholderAPI, Vault ]

commands:
  pulse:
    description: Main pulse command
    usage: /pulse <subcommand>
    permission: pulse.admin
  rank:
    description: Manage player ranks
    usage: /rank <subcommand>
    permission: pulse.rank
    aliases: [ranks]
  permission:
    description: Manage player permissions
    usage: /permission <subcommand>
    permission: pulse.permission
    aliases: [perm, perms, permissions]
  coin:
    description: Manage player coins
    usage: /coin <subcommand>
    permission: pulse.coin
    aliases: [coins, money, balance, bal]
  shop:
    description: Open the server shop
    usage: /shop [category]
    permission: pulse.shop
    aliases: [store, buy]
  tag:
    description: Manage player tags
    usage: /tag <subcommand>
    permission: pulse.tag
    aliases: [tags]
  gamemode:
    description: Change gamemode
    usage: /gamemode <mode> [player]
    permission: pulse.gamemode
    aliases: [gm]
  gmc:
    description: Change to creative mode
    usage: /gmc [player]
    permission: pulse.gamemode.creative
  gms:
    description: Change to survival mode
    usage: /gms [player]
    permission: pulse.gamemode.survival
  gma:
    description: Change to adventure mode
    usage: /gma [player]
    permission: pulse.gamemode.adventure
  gmsp:
    description: Change to spectator mode
    usage: /gmsp [player]
    permission: pulse.gamemode.spectator
  kick:
    description: Kick a player
    usage: /kick <player> [reason]
    permission: pulse.punishment.kick
  ban:
    description: Permanently ban a player
    usage: /ban <player> [reason]
    permission: pulse.punishment.ban
  tempban:
    description: Temporarily ban a player
    usage: /tempban <player> <duration> [reason]
    permission: pulse.punishment.tempban
  ipban:
    description: Ban a player's IP address
    usage: /ipban <player> [reason]
    permission: pulse.punishment.ipban
  tempipban:
    description: Temporarily ban a player's IP
    usage: /tempipban <player> <duration> [reason]
    permission: pulse.punishment.tempipban
  unban:
    description: Unban a player
    usage: /unban <player>
    permission: pulse.punishment.unban
  mute:
    description: Mute a player
    usage: /mute <player> [duration] [reason]
    permission: pulse.punishment.mute
  unmute:
    description: Unmute a player
    usage: /unmute <player>
    permission: pulse.punishment.unmute
  freeze:
    description: Freeze a player
    usage: /freeze <player>
    permission: pulse.punishment.freeze
  unfreeze:
    description: Unfreeze a player
    usage: /unfreeze <player>
    permission: pulse.punishment.freeze
  warn:
    description: Warn a player
    usage: /warn <player> <reason>
    permission: pulse.punishment.warn
  warns:
    description: View player warnings
    usage: /warns <player>
    permission: pulse.punishment.warns
  unwarn:
    description: Remove a player's latest warning
    usage: /unwarn <player>
    permission: pulse.punishment.unwarn
  grant:
    description: Grant ranks to players with a GUI
    usage: /grant <player>
    permission: pulse.grant
  playtime:
    description: View playtime statistics
    usage: /playtime [player]
    permission: pulse.playtime
  profile:
    description: View player profile
    usage: /profile [player]
    permission: pulse.profile
  report:
    description: Report a player
    usage: /report <player> <reason>
    permission: pulse.report

permissions:
  pulse.*:
    description: All pulse permissions
    children:
      pulse.admin: true
      pulse.rank: true
      pulse.grant: true
      pulse.permission: true
      pulse.coin: true
      pulse.shop: true
      pulse.tag: true
      pulse.chat.color: true
      pulse.playtime: true
      pulse.playtime.others: true
  pulse.admin:
    description: Administrator access to pulse
  pulse.rank:
    description: Access to rank commands
    children:
      pulse.rank.create: true
      pulse.rank.delete: true
      pulse.rank.set: true
      pulse.rank.info: true
      pulse.rank.list: true
      pulse.rank.permission: true
      pulse.rank.reload: true
  pulse.rank.create:
    description: Create new ranks
  pulse.rank.delete:
    description: Delete existing ranks
  pulse.rank.set:
    description: Set player ranks
  pulse.rank.info:
    description: View rank information
  pulse.rank.list:
    description: List all ranks
  pulse.rank.permission:
    description: Manage rank permissions
  pulse.rank.reload:
    description: Reload rank system
  pulse.grant:
    description: Grant ranks to players with GUI
  pulse.permission:
    description: Access to permission commands
    children:
      pulse.permission.add: true
      pulse.permission.remove: true
      pulse.permission.deny: true
      pulse.permission.check: true
      pulse.permission.list: true
  pulse.permission.add:
    description: Add permissions to players
  pulse.permission.remove:
    description: Remove permissions from players
  pulse.permission.deny:
    description: Deny permissions for players
  pulse.permission.check:
    description: Check player permissions
  pulse.permission.list:
    description: List player permissions
  pulse.coin:
    description: Access to coin commands
    children:
      pulse.coin.pay: true
  pulse.coin.add:
    description: Add coins to players
  pulse.coin.remove:
    description: Remove coins from players
  pulse.coin.set:
    description: Set player coin balances
  pulse.coin.pay:
    description: Pay other players
  pulse.coin.top:
    description: View balance leaderboard
  pulse.coin.others:
    description: Check other players' balances
  pulse.shop:
    description: Access to shop
    children:
      pulse.shop.use: true
  pulse.shop.use:
    description: Use the shop
  pulse.shop.reload:
    description: Reload shop configuration
  pulse.shop.list:
    description: List shop items
  pulse.tag:
    description: Access to tag commands
    children:
      pulse.tag.others: true
      pulse.tag.give: true
      pulse.tag.remove: true
      pulse.tag.create: true
      pulse.tag.edit: true
      pulse.tag.delete: true
      pulse.tag.reload: true
  pulse.tag.others:
    description: View other players' tags
  pulse.tag.give:
    description: Give tags to players
  pulse.tag.remove:
    description: Remove tags from players
  pulse.tag.create:
    description: Create new tags
  pulse.tag.edit:
    description: Edit existing tags
  pulse.tag.delete:
    description: Delete tags
  pulse.tag.reload:
    description: Reload tag system
  pulse.chat.color:
    description: Use color codes in chat messages
  pulse.gamemode:
    description: Change gamemode
    children:
      pulse.gamemode.creative: true
      pulse.gamemode.survival: true
      pulse.gamemode.adventure: true
      pulse.gamemode.spectator: true
      pulse.gamemode.others: true
  pulse.gamemode.creative:
    description: Change to creative mode
  pulse.gamemode.survival:
    description: Change to survival mode
  pulse.gamemode.adventure:
    description: Change to adventure mode
  pulse.gamemode.spectator:
    description: Change to spectator mode
  pulse.gamemode.others:
    description: Change others' gamemode
  pulse.punishment:
    description: All punishment permissions
    children:
      pulse.punishment.kick: true
      pulse.punishment.warn: true
      pulse.punishment.warns: true
      pulse.punishment.unwarn: true
      pulse.punishment.mute: true
      pulse.punishment.unmute: true
      pulse.punishment.freeze: true
      pulse.punishment.tempban: true
      pulse.punishment.ban: true
      pulse.punishment.unban: true
      pulse.punishment.ipban: true
      pulse.punishment.tempipban: true
  pulse.punishment.kick:
    description: Kick players
  pulse.punishment.warn:
    description: Warn players
  pulse.punishment.warns:
    description: View player warnings
  pulse.punishment.unwarn:
    description: Remove warnings
  pulse.punishment.mute:
    description: Mute players
  pulse.punishment.unmute:
    description: Unmute players
  pulse.punishment.freeze:
    description: Freeze/unfreeze players
  pulse.punishment.tempban:
    description: Temporarily ban players
  pulse.punishment.ban:
    description: Permanently ban players
  pulse.punishment.unban:
    description: Unban players
  pulse.punishment.ipban:
    description: IP ban players
  pulse.punishment.tempipban:
    description: Temporarily IP ban players
  pulse.playtime:
    description: View own playtime
  pulse.playtime.others:
    description: View other players' playtime
  pulse.update.notify:
    description: Receive update notifications on join
  pulse.profile:
    description: View own profile
  pulse.profile.others:
    description: View other players' profiles
  pulse.profile.staff:
    description: Access staff-only features in profiles
  pulse.report:
    description: Report players
  pulse.reports.notify:
    description: Receive notifications when players are reported