name: Pulse
version: '${version}'
main: dev.aledlb.pulse.Pulse
api-version: '1.21'
folia-supported: true
load: STARTUP
authors: [ aledlb ]
description: Advanced server core plugin with modular architecture
website: https://github.com/aledlb8/pulse
softdepend: [ PlaceholderAPI, Vault ]

libraries:
  # Kotlin
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.20
  # Configuration
  - org.spongepowered:configurate-yaml:4.1.2
  - org.spongepowered:configurate-extra-kotlin:4.1.2
  # Database
  - org.jetbrains.exposed:exposed-core:0.44.1
  - org.jetbrains.exposed:exposed-dao:0.44.1
  - org.jetbrains.exposed:exposed-jdbc:0.44.1
  - org.jetbrains.exposed:exposed-java-time:0.44.1
  - com.zaxxer:HikariCP:5.0.1
  - org.xerial:sqlite-jdbc:3.44.1.0
  - com.mysql:mysql-connector-j:8.2.0
  - org.postgresql:postgresql:42.7.7
  # Redis
  - redis.clients:jedis:5.1.0
  # Coroutines
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3
  # Logging
  - ch.qos.logback:logback-classic:1.5.13

commands:
  pulse:
    description: Main pulse command
    usage: /pulse <subcommand>
    permission: pulse.admin
  rank:
    description: Manage player ranks
    usage: /rank <subcommand>
    permission: pulse.rank
    aliases: [ranks]
  permission:
    description: Manage player permissions
    usage: /permission <subcommand>
    permission: pulse.permission
    aliases: [perm, perms, permissions]
  coin:
    description: Manage player coins
    usage: /coin <subcommand>
    permission: pulse.coin
    aliases: [coins, money, balance, bal]
  shop:
    description: Open the server shop
    usage: /shop [category]
    permission: pulse.shop
  tag:
    description: Manage player tags
    usage: /tag <subcommand>
    permission: pulse.tag
    aliases: [tags]
  gamemode:
    description: Change gamemode
    usage: /gamemode <mode> [player]
    permission: pulse.gamemode
    aliases: [gm]
  gmc:
    description: Change to creative mode
    usage: /gmc [player]
    permission: pulse.gamemode.creative
  gms:
    description: Change to survival mode
    usage: /gms [player]
    permission: pulse.gamemode.survival
  gma:
    description: Change to adventure mode
    usage: /gma [player]
    permission: pulse.gamemode.adventure
  gmsp:
    description: Change to spectator mode
    usage: /gmsp [player]
    permission: pulse.gamemode.spectator
  kick:
    description: Kick a player
    usage: /kick <player> [reason]
    permission: pulse.punishment.kick
  ban:
    description: Permanently ban a player
    usage: /ban <player> [reason]
    permission: pulse.punishment.ban
  tempban:
    description: Temporarily ban a player
    usage: /tempban <player> <duration> [reason]
    permission: pulse.punishment.tempban
  ipban:
    description: Ban a player's IP address
    usage: /ipban <player> [reason]
    permission: pulse.punishment.ipban
  tempipban:
    description: Temporarily ban a player's IP
    usage: /tempipban <player> <duration> [reason]
    permission: pulse.punishment.tempipban
  unban:
    description: Unban a player
    usage: /unban <player>
    permission: pulse.punishment.unban
  mute:
    description: Mute a player
    usage: /mute <player> [duration] [reason]
    permission: pulse.punishment.mute
  unmute:
    description: Unmute a player
    usage: /unmute <player>
    permission: pulse.punishment.unmute
  freeze:
    description: Freeze a player
    usage: /freeze <player>
    permission: pulse.punishment.freeze
  unfreeze:
    description: Unfreeze a player
    usage: /unfreeze <player>
    permission: pulse.punishment.freeze
  warn:
    description: Warn a player
    usage: /warn <player> <reason>
    permission: pulse.punishment.warn
  warns:
    description: View player warnings
    usage: /warns <player>
    permission: pulse.punishment.warns
  unwarn:
    description: Remove a player's latest warning
    usage: /unwarn <player>
    permission: pulse.punishment.unwarn
  grant:
    description: Grant ranks to players with a GUI
    usage: /grant <player>
    permission: pulse.grant
  playtime:
    description: View playtime statistics
    usage: /playtime [player]
    permission: pulse.playtime
  profile:
    description: View player profile
    usage: /profile [player]
    permission: pulse.profile
  report:
    description: Report a player
    usage: /report <player> <reason>
    permission: pulse.report
  motd:
    description: Manage MOTD settings
    usage: /motd <reload|maintenance>
    permission: pulse.motd

permissions:
  pulse.*:
    description: All pulse permissions
    default: op
    children:
      pulse.admin: true
      pulse.rank: true
      pulse.grant: true
      pulse.permission: true
      pulse.coin: true
      pulse.shop: true
      pulse.tag: true
      pulse.chat.color: true
      pulse.gamemode: true
      pulse.punishment: true
      pulse.playtime: true
      pulse.playtime.others: true
      pulse.profile: true
      pulse.profile.others: true
      pulse.profile.staff: true
      pulse.report: true
      pulse.reports.notify: true
      pulse.update.notify: true
      pulse.motd: true
      pulse.maintenance.bypass: true
  pulse.admin:
    description: Administrator access to pulse
    default: false
  pulse.rank:
    description: Access to rank commands
    default: false
    children:
      pulse.rank.create: true
      pulse.rank.delete: true
      pulse.rank.remove: true
      pulse.rank.set: true
      pulse.rank.info: true
      pulse.rank.list: true
      pulse.rank.permission: true
      pulse.rank.reload: true
  pulse.rank.create:
    description: Create new ranks
    default: false
  pulse.rank.delete:
    description: Delete existing ranks
    default: false
  pulse.rank.remove:
    description: Remove player ranks
    default: false
  pulse.rank.set:
    description: Set player ranks
    default: false
  pulse.rank.info:
    description: View rank information
    default: false
  pulse.rank.list:
    description: List all ranks
    default: false
  pulse.rank.permission:
    description: Manage rank permissions
    default: false
  pulse.rank.reload:
    description: Reload rank system
    default: false
  pulse.grant:
    description: Grant ranks to players with GUI
    default: false
  pulse.permission:
    description: Access to permission commands
    default: false
    children:
      pulse.permission.add: true
      pulse.permission.remove: true
      pulse.permission.deny: true
      pulse.permission.check: true
      pulse.permission.list: true
  pulse.permission.add:
    description: Add permissions to players
    default: false
  pulse.permission.remove:
    description: Remove permissions from players
    default: false
  pulse.permission.deny:
    description: Deny permissions for players
    default: false
  pulse.permission.check:
    description: Check player permissions
    default: false
  pulse.permission.list:
    description: List player permissions
    default: false
  pulse.coin:
    description: Access to coin commands
    default: false
    children:
      pulse.coin.add: true
      pulse.coin.remove: true
      pulse.coin.set: true
      pulse.coin.pay: true
      pulse.coin.top: true
      pulse.coin.others: true
  pulse.coin.add:
    description: Add coins to players
    default: false
  pulse.coin.remove:
    description: Remove coins from players
    default: false
  pulse.coin.set:
    description: Set player coin balances
    default: false
  pulse.coin.pay:
    description: Pay other players
    default: false
  pulse.coin.top:
    description: View balance leaderboard
    default: false
  pulse.coin.others:
    description: Check other players' balances
    default: false
  pulse.shop:
    description: Access to shop
    default: false
    children:
      pulse.shop.use: true
  pulse.shop.use:
    description: Use the shop
    default: false
  pulse.shop.reload:
    description: Reload shop configuration
    default: false
  pulse.shop.list:
    description: List shop items
    default: false
  pulse.tag:
    description: Access to tag commands
    default: false
    children:
      pulse.tag.others: true
      pulse.tag.give: true
      pulse.tag.remove: true
      pulse.tag.create: true
      pulse.tag.edit: true
      pulse.tag.delete: true
      pulse.tag.reload: true
  pulse.tag.others:
    description: View other players' tags
    default: false
  pulse.tag.give:
    description: Give tags to players
    default: false
  pulse.tag.remove:
    description: Remove tags from players
    default: false
  pulse.tag.create:
    description: Create new tags
    default: false
  pulse.tag.edit:
    description: Edit existing tags
    default: false
  pulse.tag.delete:
    description: Delete tags
    default: false
  pulse.tag.reload:
    description: Reload tag system
    default: false
  pulse.chat.color:
    description: Use color codes in chat messages
    default: false
  pulse.gamemode:
    description: Change gamemode
    default: false
    children:
      pulse.gamemode.creative: true
      pulse.gamemode.survival: true
      pulse.gamemode.adventure: true
      pulse.gamemode.spectator: true
      pulse.gamemode.others: true
  pulse.gamemode.creative:
    description: Change to creative mode
    default: false
  pulse.gamemode.survival:
    description: Change to survival mode
    default: false
  pulse.gamemode.adventure:
    description: Change to adventure mode
    default: false
  pulse.gamemode.spectator:
    description: Change to spectator mode
    default: false
  pulse.gamemode.others:
    description: Change others' gamemode
    default: false
  pulse.punishment:
    description: All punishment permissions
    default: false
    children:
      pulse.punishment.kick: true
      pulse.punishment.warn: true
      pulse.punishment.warns: true
      pulse.punishment.unwarn: true
      pulse.punishment.mute: true
      pulse.punishment.unmute: true
      pulse.punishment.freeze: true
      pulse.punishment.tempban: true
      pulse.punishment.ban: true
      pulse.punishment.unban: true
      pulse.punishment.ipban: true
      pulse.punishment.tempipban: true
  pulse.punishment.kick:
    description: Kick players
    default: false
  pulse.punishment.warn:
    description: Warn players
    default: false
  pulse.punishment.warns:
    description: View player warnings
    default: false
  pulse.punishment.unwarn:
    description: Remove warnings
    default: false
  pulse.punishment.mute:
    description: Mute players
    default: false
  pulse.punishment.unmute:
    description: Unmute players
    default: false
  pulse.punishment.freeze:
    description: Freeze/unfreeze players
    default: false
  pulse.punishment.tempban:
    description: Temporarily ban players
    default: false
  pulse.punishment.ban:
    description: Permanently ban players
    default: false
  pulse.punishment.unban:
    description: Unban players
    default: false
  pulse.punishment.ipban:
    description: IP ban players
    default: false
  pulse.punishment.tempipban:
    description: Temporarily IP ban players
    default: false
  pulse.playtime:
    description: View own playtime
    default: false
  pulse.playtime.others:
    description: View other players' playtime
    default: false
  pulse.update.notify:
    description: Receive update notifications on join
    default: false
  pulse.profile:
    description: View own profile
    default: false
  pulse.profile.others:
    description: View other players' profiles
    default: false
  pulse.profile.staff:
    description: Access staff-only features in profiles
    default: false
  pulse.report:
    description: Report players
    default: false
  pulse.reports.notify:
    description: Receive notifications when players are reported
    default: false
  pulse.motd:
    description: Access to MOTD commands
    default: false
    children:
      pulse.motd.reload: true
      pulse.motd.maintenance: true
  pulse.motd.reload:
    description: Reload MOTD configuration
    default: false
  pulse.motd.maintenance:
    description: Toggle maintenance mode
    default: false
  pulse.maintenance.bypass:
    description: Bypass maintenance mode and join the server
    default: false
